import pandas as pd
from functools import partial
from .coin_timeseries import map_id_and_field_to_transformed_timeseries, map_id_and_field_and_interval_to_transformed_timeseries, map_id_to_transformed_timeseries


# get_usdbtc = partial(map_id_and_field_to_transformed_timeseries, "bitcoin", "prices", "usd")
# get_usdbtc_minutely = partial(map_id_and_field_and_interval_to_transformed_timeseries, "bitcoin", "prices", "usd", "5m")
# get_usdbtc_hourly = partial(map_id_and_field_and_interval_to_transformed_timeseries, "bitcoin", "prices", "usd", "hourly")
# get_usdbtc_daily = partial(map_id_and_field_and_interval_to_transformed_timeseries, "bitcoin", "prices", "usd", "daily")
# get_usdbtc_1d = partial(map_id_and_field_to_transformed_timeseries, "bitcoin", "prices", "usd", "1D")
# get_usdbtc_7d = partial(map_id_and_field_to_transformed_timeseries, "bitcoin", "prices", "usd", "7D")
# get_usdbtc_30d = partial(map_id_and_field_to_transformed_timeseries, "bitcoin", "prices", "usd", "30D")
# get_usdbtc_90d = partial(map_id_and_field_to_transformed_timeseries, "bitcoin", "prices", "usd", "90D")
# get_usdbtc_180d = partial(map_id_and_field_to_transformed_timeseries, "bitcoin", "prices", "usd", "180D")
# get_usdbtc_1y = partial(map_id_and_field_to_transformed_timeseries, "bitcoin", "prices", "usd", "1Y")
# get_usdbtc_max = partial(map_id_and_field_to_transformed_timeseries, "bitcoin", "prices", "usd", "MAX")

# get_krwbtc = partial(map_id_and_field_to_transformed_timeseries, "bitcoin", "prices", "krw")
# get_krwbtc_1d = partial(map_id_and_field_to_transformed_timeseries, "bitcoin", "prices", "krw", "1D")
# get_krwbtc_7d = partial(map_id_and_field_to_transformed_timeseries, "bitcoin", "prices", "krw", "7D")
# get_krwbtc_30d = partial(map_id_and_field_to_transformed_timeseries, "bitcoin", "prices", "krw", "30D")
# get_krwbtc_90d = partial(map_id_and_field_to_transformed_timeseries, "bitcoin", "prices", "krw", "90D")
# get_krwbtc_180d = partial(map_id_and_field_to_transformed_timeseries, "bitcoin", "prices", "krw", "180D")
# get_krwbtc_1y = partial(map_id_and_field_to_transformed_timeseries, "bitcoin", "prices", "krw", "1Y")
# get_krwbtc_max = partial(map_id_and_field_to_transformed_timeseries, "bitcoin", "prices", "krw", "MAX")

# get_usdeth = partial(map_id_and_field_to_transformed_timeseries, "ethereum", "prices", "usd")
# get_usdeth_1d = partial(map_id_and_field_to_transformed_timeseries, "ethereum", "prices", "usd", "1D")
# get_usdeth_7d = partial(map_id_and_field_to_transformed_timeseries, "ethereum", "prices", "usd", "7D")
# get_usdeth_30d = partial(map_id_and_field_to_transformed_timeseries, "ethereum", "prices", "usd", "30D")
# get_usdeth_90d = partial(map_id_and_field_to_transformed_timeseries, "ethereum", "prices", "usd", "90D")
# get_usdeth_180d = partial(map_id_and_field_to_transformed_timeseries, "ethereum", "prices", "usd", "180D")
# get_usdeth_1y = partial(map_id_and_field_to_transformed_timeseries, "ethereum", "prices", "usd", "1Y")
# get_usdeth_max = partial(map_id_and_field_to_transformed_timeseries, "ethereum", "prices", "usd", "MAX")

# get_krweth_1d = partial(map_id_and_field_to_transformed_timeseries, "ethereum", "prices", "krw", "1D")
# get_krweth_7d = partial(map_id_and_field_to_transformed_timeseries, "ethereum", "prices", "krw", "7D")
# get_krweth_30d = partial(map_id_and_field_to_transformed_timeseries, "ethereum", "prices", "krw", "30D")
# get_krweth_90d = partial(map_id_and_field_to_transformed_timeseries, "ethereum", "prices", "krw", "90D")
# get_krweth_180d = partial(map_id_and_field_to_transformed_timeseries, "ethereum", "prices", "krw", "180D")
# get_krweth_1y = partial(map_id_and_field_to_transformed_timeseries, "ethereum", "prices", "krw", "1Y")
# get_krweth_max = partial(map_id_and_field_to_transformed_timeseries, "ethereum", "prices", "krw", "MAX")

# get_btceth = partial(map_id_and_field_to_transformed_timeseries, "ethereum", "prices", "btc")
# get_btceth_1d = partial(map_id_and_field_to_transformed_timeseries, "ethereum", "prices", "btc", "1D")
# get_btceth_7d = partial(map_id_and_field_to_transformed_timeseries, "ethereum", "prices", "btc", "7D")
# get_btceth_30d = partial(map_id_and_field_to_transformed_timeseries, "ethereum", "prices", "btc", "30D")
# get_btceth_90d = partial(map_id_and_field_to_transformed_timeseries, "ethereum", "prices", "btc", "90D")
# get_btceth_180d = partial(map_id_and_field_to_transformed_timeseries, "ethereum", "prices", "btc", "180D")
# get_btceth_1y = partial(map_id_and_field_to_transformed_timeseries, "ethereum", "prices", "btc", "1Y")
# get_btceth_max = partial(map_id_and_field_to_transformed_timeseries, "ethereum", "prices", "btc", "MAX")

# get_usdsui = partial(map_id_and_field_to_transformed_timeseries, "sui", "prices", "usd")
# get_usdsui_1d = partial(map_id_and_field_to_transformed_timeseries, "sui", "prices", "usd", "1D")
# get_usdsui_7d = partial(map_id_and_field_to_transformed_timeseries, "sui", "prices", "usd", "7D")
# get_usdsui_30d = partial(map_id_and_field_to_transformed_timeseries, "sui", "prices", "usd", "30D")
# get_usdsui_90d = partial(map_id_and_field_to_transformed_timeseries, "sui", "prices", "usd", "90D")
# get_usdsui_180d = partial(map_id_and_field_to_transformed_timeseries, "sui", "prices", "usd", "180D")
# get_usdsui_1y = partial(map_id_and_field_to_transformed_timeseries, "sui", "prices", "usd", "1Y")
# get_usdsui_max = partial(map_id_and_field_to_transformed_timeseries, "sui", "prices", "usd", "MAX")

# get_krwsui = partial(map_id_and_field_to_transformed_timeseries, "sui", "prices", "krw")
# get_krwsui_1d = partial(map_id_and_field_to_transformed_timeseries, "sui", "prices", "krw", "1D")
# get_krwsui_7d = partial(map_id_and_field_to_transformed_timeseries, "sui", "prices", "krw", "7D")
# get_krwsui_30d = partial(map_id_and_field_to_transformed_timeseries, "sui", "prices", "krw", "30D")
# get_krwsui_90d = partial(map_id_and_field_to_transformed_timeseries, "sui", "prices", "krw", "90D")
# get_krwsui_180d = partial(map_id_and_field_to_transformed_timeseries, "sui", "prices", "krw", "180D")
# get_krwsui_1y = partial(map_id_and_field_to_transformed_timeseries, "sui", "prices", "krw", "1Y")
# get_krwsui_max = partial(map_id_and_field_to_transformed_timeseries, "sui", "prices", "krw", "MAX")

# get_btcsui = partial(map_id_and_field_to_transformed_timeseries, "sui", "prices", "btc")
# get_btcsui_1d = partial(map_id_and_field_to_transformed_timeseries, "sui", "prices", "btc", "1D")
# get_btcsui_7d = partial(map_id_and_field_to_transformed_timeseries, "sui", "prices", "btc", "7D")
# get_btcsui_30d = partial(map_id_and_field_to_transformed_timeseries, "sui", "prices", "btc", "30D")
# get_btcsui_90d = partial(map_id_and_field_to_transformed_timeseries, "sui", "prices", "btc", "90D")
# get_btcsui_180d = partial(map_id_and_field_to_transformed_timeseries, "sui", "prices", "btc", "180D")
# get_btcsui_1y = partial(map_id_and_field_to_transformed_timeseries, "sui", "prices", "btc", "1Y")
# get_btcsui_max = partial(map_id_and_field_to_transformed_timeseries, "sui", "prices", "btc", "MAX")